version: '3'

services:

  kanboard:
    image: kanboard/kanboard
    volumes:
      - ./data:/var/www/app/data
      - ./plugins:/var/www/app/plugins
      - ./config.php:/var/www/app/config.php
    ports:
      - 8080:80

